# Generated by Django 2.2.4 on 2020-02-09 14:21

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
