# Generated by Django 2.2.4 on 2020-02-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='product_photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
