# Generated by Django 2.2.4 on 2020-02-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product_intermediary',
            name='quantity',
            field=models.CharField(max_length=8),
        ),
    ]
