# Generated by Django 2.2.4 on 2020-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200215_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product_intermediary',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
